name: Deploy to Master

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  payload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Extract Commit Hash from Push
        run: echo "COMMIT_HASH=$(git rev-parse --short "$SHA")" >> $GITHUB_ENV
        env:
          SHA: ${{ github.event.pull_request.head.sha }}

      - name: Output Commit Hash
        run: echo $COMMIT_HASH

      - name: Extract Commit Hash from PR
        run: echo "PR_COMMIT_HASH=$(git rev-parse --short "$(jq -r '.commits[-2].id' $GITHUB_EVENT_PATH)")" >> $GITHUB_ENV

      - name: Output PR Commit Hash
        run: echo $PR_COMMIT_HASH
