name: Deploy to Master

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  payload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Extract Commit Hash from Push
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short "${{github.event.pull_request.repo.sha}}")" >> $GITHUB_ENV
          echo $COMMIT_HASH

      - name: Extract Commit Hash from PR
        run: |
          echo "PR_COMMIT_HASH=$(git rev-parse --short "${{ github.event.commits[0].id }}")" >> $GITHUB_ENV
          echo $PR_COMMIT_HASH
