name: Deploy to Master

on:
  push:
    branches: [ master ]

jobs:

  payload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Extract Commit Hash
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short "${{ github.event.commits.0.id }}" >> $GITHUB_ENV
          echo $COMMIT_HASH
          
          

#      - name: Tag Commit Container as Staging
#        run: ./.github/tag-remote-image.sh $COMMIT_HASH staging
